version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    groups:
      actions-minor:
        patterns: ["actions/*", "*/*@v*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:15"
      timezone: "Europe/Warsaw"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    commit-message:
      prefix: "deps"
      include: "scope"
    groups:
      next-ecosystem:
        patterns: ["next", "@next/*", "react", "react-dom"]
      linting:
        patterns: ["@biomejs/*", "eslint*", "@typescript-eslint/*"]
