version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 1
    labels: [deps, actions]
    groups:
      actions-minor:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:15"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 1
    versioning-strategy: increase-if-necessary
    commit-message: { prefix: deps, include: scope }
    labels: [deps, npm]
    groups:
      all-minor-patch:
        patterns: ["*"]
        update-types: [minor, patch]
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
        update-types: [version-update:semver-major]