name: content-ci
on:
  pull_request:
    paths:
      - 'content/**'
      - 'public/media/**'
  push:
    branches: [main]
    paths:
      - 'content/**'
      - 'public/media/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install deps
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Build
        run: pnpm run build
