name: content-ci
on:
  pull_request:
    paths:
      - "content/**"
      - "public/media/**"
  push:
    branches: [main]
    paths:
      - "content/**"
      - "public/media/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: "pnpm" }
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
      - name: Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: ./lighthouserc.json
          uploadArtifacts: true
